"""Describe your changes

Revision ID: 1706c6bb2277
Revises: 22868b1cced2
Create Date: 2024-10-23 14:50:27.091133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1706c6bb2277'
down_revision: Union[str, None] = '22868b1cced2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topicsPreferences', sa.Column('country_code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'topicsPreferences', ['id'])
    op.create_unique_constraint(None, 'userQueries', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userQueries', type_='unique')
    op.drop_constraint(None, 'topicsPreferences', type_='unique')
    op.drop_column('topicsPreferences', 'country_code')
    # ### end Alembic commands ###
