google_search_operator = (
    "<b>Google Search Operators: Basic and Advanced</b>\n\n"
    "<b>Basic Operators:</b>\n"
    "1. <b>Quotes (\"\"):</b> Search for an exact phrase or word.\n"
    "   Example: <code>\"science tutor\"</code> will show results with this exact phrase.\n\n"
    "2. <b>Minus (-):</b> Exclude specific words from your search.\n"
    "   Example: <code>science tutor -chemistry</code> will exclude results related to chemistry.\n\n"
    "3. <b>OR:</b> Search for one of multiple terms.\n"
    "   Example: <code>science tutor OR math tutor</code> will show results for either science or math tutors.\n\n"
    "4. <b>Site (site:):</b> Search within a specific website.\n"
    "   Example: <code>site:wikipedia.org science</code> will search for \"science\" only on Wikipedia.\n\n"
    "5. <b>Asterisk (*):</b> Use as a wildcard to fill in unknown or variable words.\n"
    "   Example: <code>\"science * tutor\"</code> will find results like \"science subject tutor\" or \"science exam tutor.\"\n\n"
    "<b>Advanced Operators:</b>\n"
    "1. <b>Filetype (filetype:):</b> Find specific file types like PDFs, DOCs, etc.\n"
    "   Example: <code>science notes filetype:pdf</code> will show PDF files related to science notes.\n\n"
    "2. <b>Intitle (intitle:):</b> Search for pages that have a specific word in the title.\n"
    "   Example: <code>intitle:tutorial Python</code> will show pages with \"tutorial\" in the title and related to Python.\n\n"
    "3. <b>Inurl (inurl:):</b> Search for pages with a specific word in the URL.\n"
    "   Example: <code>inurl:tutorial python</code> will show results with \"tutorial\" in the URL and relevant to Python.\n\n"
    "4. <b>Related (related:):</b> Find websites related to a specific domain.\n"
    "   Example: <code>related:bbc.com</code> will show sites related to BBC.\n\n"
    "5. <b>Cache (cache:):</b> View Google's cached version of a website.\n"
    "   Example: <code>cache:wikipedia.org</code> will show the cached version of Wikipedia.\n\n"
    "6. <b>Before / After (before: YYYY or after: YYYY):</b> Search for content from a specific time range.\n"
    "   Example: <code>climate change before:2020</code> will show content about climate change before 2020.\n\n"
    "7. <b>AROUND (AROUND(n)):</b> Find terms that appear close to each other.\n"
    "   Example: <code>science AROUND(5) tutor</code> will find results where \"science\" and \"tutor\" appear within 5 words of each other.\n\n"
    "8. <b>Allintext (allintext:):</b> Search for pages that contain all specified terms in the text.\n"
    "   Example: <code>allintext:science tutor exam preparation</code> will show results containing all those words in the text.\n\n"
    "<b>Additional Tips:</b>\n"
    "• Use an asterisk (*) as a wildcard for unknown terms\n"
    "• Specify a range using .. (e.g., <code>$50..$100</code>)\n"
    "• Use <code>define:term</code> to get definitions\n"
    "• Use <code>allintitle:keywords</code> for words in title\n"
    "• Use <code>allintext:keywords</code> for words in text\n\n"
    "<b>Example Searches:</b>\n"
    "• Find PDF files about machine learning: <code>machine learning filetype:pdf</code>\n"
    "• Search within a specific website: <code>site:wikipedia.org artificial intelligence</code>\n"
    "• Exclude certain terms: <code>best smartphones -Samsung</code>\n\n"
)